# Generated by Django 5.2.8 on 2025-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="is_self_assessment",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="value",
        ),
        migrations.AddField(
            model_name="assessment",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RARELY", "Rarement"),
                    ("OFTEN", "Souvent"),
                    ("SYSTEMATICALLY", "Systématiquement"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_concerned",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="role_evaluator",
            field=models.CharField(
                choices=[
                    ("TEACHER", "Enseignant"),
                    ("STUDENT", "Étudiant"),
                    ("TUTOR", "Tuteur"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="validation_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_ACQUIRED", "Non acquis"),
                    ("IN_PROGRESS", "En cours d'acquisition"),
                    ("ACQUIRED", "Acquis"),
                    ("MASTERED", "Maîtrisé"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("PENDING_WRITING", "En attente écrit"),
                    ("PENDING_INTERVIEW", "En attente entretien"),
                    ("VALIDATED", "Validé"),
                ],
                default="PENDING_WRITING",
                max_length=20,
            ),
        ),
    ]
